# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: 'Publish Web'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\output\OctoPetShop.Web\'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish Product Service API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\output\OctoPetShop.ProductService\'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish database'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\OctopusSamples.OctoPetShop.Database\OctopusSamples.OctoPetShop.Database.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\output\OctoPetShop.Database\ --runtime win-x64'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish Shopping Cart Service'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\OctopusSamples.OctoPetShop.ShoppingCartService\OctopusSamples.OctoPetShop.ShoppingCartService.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\output\OctoPetShop.ShoppingCartService\'
    zipAfterPublish: false
    modifyOutputPath: false

- task: OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.Database'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.Database
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.Database\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.Web'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.Web
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.Web\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.ProductService'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.ProductService
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.ProductService\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: OctopusPack@4
  displayName: 'Package OctopusSamples.Octopetshop.ShoppingCartService'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.ShoppingCartService
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.ShoppingCartService\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: OctopusMetadata@4
  inputs:
        OctoConnectedServiceName: 'OctoSuperPowers'
        Space: 'Spaces-342'
        PackageId: |
          OctoPetshop.ProductService
          OctoPetShop.Web
          OctoPetShop.ShoppingCartService
          OctoPetShop.Database
        PackageVersion: '$(Build.BuildNumber)'
        Replace: 'false'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-push.OctopusPush@4
  displayName: 'Push Packages to Octopus'
  inputs:
    OctoConnectedServiceName: OctoSuperPowers
    Space: 'Spaces-342'
    Package: '$(Build.SourcesDirectory)/output/*.zip'

- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'OctoSuperPowers'
    Space: 'Spaces-342'
    ProjectGroup: 'ProjectGroups-442'
    ProjectName: 'Projects-3462'
    Channel: 'Channels-3442'
    ChangesetCommentReleaseNotes: true
    WorkItemReleaseNotes: true
