name: StorageBicepTemplate

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Bicep Build"
  BicepBuild:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    - name: Sparse Checkout
  # You may pin to the exact commit or the version.
  # uses: gogaille/sparse-checkout@3114de9b3cf84c0829fe84222d8ae8d806fbc794
    - uses: gogaille/sparse-checkout@v0.1
      with:
        patterns: '2022/bicepoctopus/Bicep-Storage-Template'
